# -*- coding: utf-8 -*-
from collections import OrderedDict

VERSION = "1.1.0"

STATS = [
    ('uptime', 'float', 'Uptime'),
    ('os_version', 'str', 'OS'),
    ('Mycodo_revision', 'str', 'Mycodo Version'),
    ('alembic_version', 'str', 'Alembic Version'),
    ('RPi_revision', 'str', 'RPi Version'),
    ('country', 'str', 'Country'),
    ('daemon_startup_seconds', 'float', 'Startup Seconds'),
    ('ram_use_mb', 'float', 'Ram Use'),
    ('num_relays', 'int', 'Number of Outputs'),
    ('num_sensors_active', 'int', 'Inputs Active'),
    ('num_sensors', 'int', 'Inputs'),
    ('num_maths_active', 'int', 'Maths Active'),
    ('num_maths', 'int', 'Maths'),
    ('num_conditionals_active', 'int', 'Conditionals Active'),
    ('num_conditionals', 'int', 'Conditionals'),
    ('num_triggers_active', 'int', 'Triggers Active'),
    ('num_triggers', 'int', 'Triggers'),
    ('num_methods_in_pid', 'int', 'Methods in PIDs'),
    ('num_methods', 'int', 'Mthods'),
    ('num_pids_active', 'int', 'PIDs Active'),
    ('num_pids', 'int', 'PIDs'),
    ('num_lcds_active', 'int', 'LCDs Active'),
    ('num_lcds', 'int', 'LCDs')
]

COLUMNS = [
    ('ID', 'id', ''),
    ('Last', 'last', ''),
    ('Up', 'uptime', ''),
    ('OS', 'os_version', ''),
    ('M.v', 'Mycodo_revision', ''),
    ('A.v', 'alembic_version', ''),
    ('Pi', 'RPi_revision', ''),
    ('Loc', 'country', ''),
    ('Strt', 'daemon_startup_seconds', ''),
    ('RAM', 'ram_use_mb', ''),
    ('Out', 'num_relays', ''),
    ('In', 'num_sensors', 'num_sensors_active'),
    ('Ma', 'num_maths', 'num_maths_active'),
    ('Con', 'num_conditionals', 'num_conditionals_active'),
    ('Tr', 'num_triggers', 'num_triggers_active'),
    ('Me', 'num_methods', 'num_methods_in_pid'),
    ('PID', 'num_pids', 'num_pids_active'),
    ('LCD', 'num_lcds', 'num_lcds_active')
]

PI_VERSIONS = {
    'Beta': '1Beta',
    '0002': '1B',
    '0003': '1B',  # ECN0001
    '0004': '1B',
    '0005': '1B',
    '0006': '1B',
    '0007': '1A',
    '0008': '1A',
    '0009': '1A',
    '0010': '1B+',
    '000d': '1B',
    '000e': '1B',
    '000f': '1B',
    '100000e': '1B',
    '0011': 'CM1',
    '0012': '1A+',
    '0013': '1B+',
    '0014': 'CM1',
    '0015': '1A+',
    '2a01041': '2B',
    'a22082': '3B',
    'a020d3': '3B+',

    '900021': '1A+',  # Sony UK
    '900032': '1B+',  # Sony UK
    '900092': 'Zero',  # Sony UK
    '900093': 'Zero',  # Sony UK
    '9000c1': 'ZeroW',  # Sony UK
    '920093': 'Zero',  # Embest
    '9020e0': '3A+',  # Sony UK
    'a01040': '2B',  # Sony UK
    'a01041': '2B',  # Sony UK

    'a02082': '3B',  # Sony UK
    'a020a0': 'CM3',  # & Lite, Sony UK
    'a52082': '3B',  # Stadium
    'a21041': '2B',  # Embest
    'a22042': '2B',  # BCM2837
    '2a21041': '2B 1.1',
    '2a02082': '3B',  # Embest
    'a32082': '3BJap',  # Japan
    '1a22082': '3BUnk',  # Unknown
    '2a020d3': '3B+',
    
    'a03111': '4B 1.1 1GB',
    'b03111': '4B 1.1 2GB',
    'c03111': '4B 1.1 4GB',
    'a03112': '4B 1.2 1GB',
    'b03112': '4B 1.2 2GB',
    'c03112': '4B 1.2 4GB',
    'b03114': '4B 1.4 2GB',
    'c03114': '4B 1.4 4GB',
    'd03114': '4B 1.4 8GB'
}

countries = OrderedDict([
    ("AF", {"name": "Afghanistan", "continent": "Asia"}),
    ("AL", {"name": "Albania", "continent": "Europe"}),
    ("DZ", {"name": "Algeria", "continent": "Africa"}),
    ("AD", {"name": "Andorra", "continent": "Europe"}),
    ("AO", {"name": "Angola", "continent": "Africa"}),
    ("AG", {"name": "Antigua and Barbuda", "continent": "North America"}),
    ("AR", {"name": "Argentina", "continent": "South America"}),
    ("AM", {"name": "Armenia", "continent": "Asia"}),
    ("AU", {"name": "Australia", "continent": "Oceania"}),
    ("AT", {"name": "Austria", "continent": "Europe"}),
    ("AZ", {"name": "Azerbaijan", "continent": "Asia"}),
    ("BS", {"name": "Bahamas", "continent": "North America"}),
    ("BH", {"name": "Bahrain", "continent": "Asia"}),
    ("BD", {"name": "Bangladesh", "continent": "Asia"}),
    ("BB", {"name": "Barbados", "continent": "North America"}),
    ("BY", {"name": "Belarus", "continent": "Europe"}),
    ("BE", {"name": "Belgium", "continent": "Europe"}),
    ("BZ", {"name": "Belize", "continent": "North America"}),
    ("BJ", {"name": "Benin", "continent": "Africa"}),
    ("BT", {"name": "Bhutan", "continent": "Asia"}),
    ("BO", {"name": "Bolivia", "continent": "South America"}),
    ("BA", {"name": "Bosnia and Herzegovina", "continent": "Europe"}),
    ("BW", {"name": "Botswana", "continent": "Africa"}),
    ("BR", {"name": "Brazil", "continent": "South America"}),
    ("BN", {"name": "Brunei Darussalam", "continent": "Asia"}),
    ("BG", {"name": "Bulgaria", "continent": "Europe"}),
    ("BF", {"name": "Burkina Faso", "continent": "Africa"}),
    ("BI", {"name": "Burundi", "continent": "Africa"}),
    ("KH", {"name": "Cambodia", "continent": "Asia"}),
    ("CM", {"name": "Cameroon", "continent": "Africa"}),
    ("CA", {"name": "Canada", "continent": "North America"}),
    ("CV", {"name": "Cape Verde", "continent": "Africa"}),
    ("CF", {"name": "Central African Republic", "continent": "Africa"}),
    ("TD", {"name": "Chad", "continent": "Africa"}),
    ("CL", {"name": "Chile", "continent": "South America"}),
    ("CN", {"name": "China", "continent": "Asia"}),
    ("CO", {"name": "Colombia", "continent": "South America"}),
    ("KM", {"name": "Comoros", "continent": "Africa"}),
    ("CR", {"name": "Costa Rica", "continent": "North America"}),
    ("HR", {"name": "Croatia", "continent": "Europe"}),
    ("CU", {"name": "Cuba", "continent": "North America"}),
    ("CY", {"name": "Cyprus", "continent": "Asia"}),
    ("CZ", {"name": "Czech Republic", "continent": "Europe"}),
    ("CI", {"name": "CÃ´te d'Ivoire", "continent": "Africa"}),
    ("CD", {"name": "Democratic Republic of the Congo", "continent": "Africa"}),
    ("DK", {"name": "Denmark", "continent": "Europe"}),
    ("DJ", {"name": "Djibouti", "continent": "Africa"}),
    ("DM", {"name": "Dominica", "continent": "North America"}),
    ("DO", {"name": "Dominican Republic", "continent": "North America"}),
    ("TL", {"name": "East Timor", "continent": "Asia"}),
    ("EC", {"name": "Ecuador", "continent": "South America"}),
    ("EG", {"name": "Egypt", "continent": "Africa"}),
    ("SV", {"name": "El Salvador", "continent": "North America"}),
    ("GQ", {"name": "Equatorial Guinea", "continent": "Africa"}),
    ("ER", {"name": "Eritrea", "continent": "Africa"}),
    ("EE", {"name": "Estonia", "continent": "Europe"}),
    ("ET", {"name": "Ethiopia", "continent": "Africa"}),
    ("FM", {"name": "Federated States of Micronesia", "continent": "Oceania"}),
    ("FJ", {"name": "Fiji", "continent": "Oceania"}),
    ("FI", {"name": "Finland", "continent": "Europe"}),
    ("FR", {"name": "France", "continent": "Europe"}),
    ("GA", {"name": "Gabon", "continent": "Africa"}),
    ("GE", {"name": "Georgia", "continent": "Asia"}),
    ("DE", {"name": "Germany", "continent": "Europe"}),
    ("GH", {"name": "Ghana", "continent": "Africa"}),
    ("GR", {"name": "Greece", "continent": "Europe"}),
    ("GD", {"name": "Grenada", "continent": "North America"}),
    ("GU", {"name": "Guam", "continent": ""}),
    ("GG", {"name": "Guernsey", "continent": ""}),
    ("GN", {"name": "Guinea", "continent": "Africa"}),
    ("GW", {"name": "Guinea-Bissau", "continent": "Africa"}),
    ("GY", {"name": "Guyana", "continent": "South America"}),
    ("GT", {"name": "Haiti", "continent": "North America"}),
    ("HN", {"name": "Honduras", "continent": "North America"}),
    ("HU", {"name": "Hungary", "continent": "Europe"}),
    ("IS", {"name": "Iceland", "continent": "Europe"}),
    ("IN", {"name": "India", "continent": "Asia"}),
    ("ID", {"name": "Indonesia", "continent": "Asia"}),
    ("IR", {"name": "Iran", "continent": "Asia"}),
    ("IQ", {"name": "Iraq", "continent": "Asia"}),
    ("IL", {"name": "Israel", "continent": "Asia"}),
    ("IT", {"name": "Italy", "continent": "Europe"}),
    ("JM", {"name": "Jamaica", "continent": "North America"}),
    ("JP", {"name": "Japan", "continent": "Asia"}),
    ("JO", {"name": "Jordan", "continent": "Asia"}),
    ("KZ", {"name": "Kazakhstan", "continent": "Asia"}),
    ("KE", {"name": "Kenya", "continent": "Africa"}),
    ("KI", {"name": "Kiribati", "continent": "Oceania"}),
    ("KW", {"name": "Kuwait", "continent": "Asia"}),
    ("KG", {"name": "Kyrgyzstan", "continent": "Asia"}),
    ("LA", {"name": "Laos", "continent": "Asia"}),
    ("LV", {"name": "Latvia", "continent": "Europe"}),
    ("LB", {"name": "Lebanon", "continent": "Asia"}),
    ("LS", {"name": "Lesotho", "continent": "Africa"}),
    ("LR", {"name": "Liberia", "continent": "Africa"}),
    ("LY", {"name": "Libya", "continent": "Africa"}),
    ("LI", {"name": "Liechtenstein", "continent": "Europe"}),
    ("LT", {"name": "Lithuania", "continent": "Europe"}),
    ("LU", {"name": "Luxembourg", "continent": "Europe"}),
    ("MK", {"name": "Macedonia", "continent": "Europe"}),
    ("MG", {"name": "Madagascar", "continent": "Africa"}),
    ("MW", {"name": "Malawi", "continent": "Africa"}),
    ("MY", {"name": "Malaysia", "continent": "Asia"}),
    ("MV", {"name": "Maldives", "continent": "Asia"}),
    ("ML", {"name": "Mali", "continent": "Africa"}),
    ("MT", {"name": "Malta", "continent": "Europe"}),
    ("MH", {"name": "Marshall Islands", "continent": "Oceania"}),
    ("MR", {"name": "Mauritania", "continent": "Africa"}),
    ("MU", {"name": "Mauritius", "continent": "Africa"}),
    ("MX", {"name": "Mexico", "continent": "North America"}),
    ("MD", {"name": "Moldova", "continent": "Europe"}),
    ("MC", {"name": "Monaco", "continent": "Europe"}),
    ("MN", {"name": "Mongolia", "continent": "Asia"}),
    ("ME", {"name": "Montenegro", "continent": "Europe"}),
    ("MA", {"name": "Morocco", "continent": "Africa"}),
    ("MZ", {"name": "Mozambique", "continent": "Africa"}),
    ("MM", {"name": "Myanmar", "continent": "Asia"}),
    ("NA", {"name": "Namibia", "continent": "Africa"}),
    ("NR", {"name": "Nauru", "continent": "Oceania"}),
    ("NP", {"name": "Nepal", "continent": "Asia"}),
    ("NL", {"name": "Netherlands", "continent": "Europe"}),
    ("NZ", {"name": "New Zealand", "continent": "Oceania"}),
    ("NI", {"name": "Nicaragua", "continent": "North America"}),
    ("NE", {"name": "Niger", "continent": "Africa"}),
    ("NG", {"name": "Nigeria", "continent": "Africa"}),
    ("KP", {"name": "North Korea", "continent": "Asia"}),
    ("NO", {"name": "Norway", "continent": "Europe"}),
    ("OM", {"name": "Oman", "continent": "Asia"}),
    ("PK", {"name": "Pakistan", "continent": "Asia"}),
    ("PW", {"name": "Palau", "continent": "Oceania"}),
    ("PA", {"name": "Panama", "continent": "North America"}),
    ("PG", {"name": "Papua New Guinea", "continent": "Oceania"}),
    ("PY", {"name": "Paraguay", "continent": "South America"}),
    ("PE", {"name": "Peru", "continent": "South America"}),
    ("PH", {"name": "Philippines", "continent": "Asia"}),
    ("PL", {"name": "Poland", "continent": "Europe"}),
    ("PT", {"name": "Portugal", "continent": "Europe"}),
    ("PR", {"name": "Puerto Rico", "continent": "North America"}),
    ("QA", {"name": "Qatar", "continent": "Asia"}),
    ("IE", {"name": "Republic of Ireland", "continent": "Europe"}),
    ("CG", {"name": "Republic of the Congo", "continent": "Africa"}),
    ("RE", {"name": "Réunion Island", "continent": ""}),
    ("RO", {"name": "Romania", "continent": "Europe"}),
    ("RU", {"name": "Russia", "continent": "Europe"}),
    ("RW", {"name": "Rwanda", "continent": "Africa"}),
    ("KN", {"name": "Saint Kitts and Nevis", "continent": "North America"}),
    ("LC", {"name": "Saint Lucia", "continent": "North America"}),
    ("VC", {"name": "Saint Vincent and the Grenadines", "continent": "North America"}),
    ("WS", {"name": "Samoa", "continent": "Oceania"}),
    ("SM", {"name": "San Marino", "continent": "Europe"}),
    ("SA", {"name": "Saudi Arabia", "continent": "Asia"}),
    ("SN", {"name": "Senegal", "continent": "Africa"}),
    ("RS", {"name": "Serbia", "continent": "Europe"}),
    ("SC", {"name": "Seychelles", "continent": "Africa"}),
    ("SL", {"name": "Sierra Leone", "continent": "Africa"}),
    ("SG", {"name": "Singapore", "continent": "Asia"}),
    ("SK", {"name": "Slovakia", "continent": "Europe"}),
    ("SI", {"name": "Slovenia", "continent": "Europe"}),
    ("SB", {"name": "Solomon Islands", "continent": "Oceania"}),
    ("SO", {"name": "Somalia", "continent": "Africa"}),
    ("ZA", {"name": "South Africa", "continent": "Africa"}),
    ("KR", {"name": "South Korea", "continent": "Asia"}),
    ("ES", {"name": "Spain", "continent": "Europe"}),
    ("LK", {"name": "Sri Lanka", "continent": "Asia"}),
    ("SD", {"name": "Sudan", "continent": "Africa"}),
    ("SR", {"name": "Suriname", "continent": "South America"}),
    ("SZ", {"name": "Swaziland", "continent": "Africa"}),
    ("SE", {"name": "Sweden", "continent": "Europe"}),
    ("CH", {"name": "Switzerland", "continent": "Europe"}),
    ("SY", {"name": "Syria", "continent": "Asia"}),
    ("ST", {"name": "SÃ£o TomÃ© and PrÃ­ncipe", "continent": "Africa"}),
    ("TJ", {"name": "Tajikistan", "continent": "Asia"}),
    ("TZ", {"name": "Tanzania", "continent": "Africa"}),
    ("TH", {"name": "Thailand", "continent": "Asia"}),
    ("GM", {"name": "The Gambia", "continent": "Africa"}),
    ("TG", {"name": "Togo", "continent": "Africa"}),
    ("TO", {"name": "Tonga", "continent": "Oceania"}),
    ("TT", {"name": "Trinidad and Tobago", "continent": "North America"}),
    ("TN", {"name": "Tunisia", "continent": "Africa"}),
    ("TR", {"name": "Turkey", "continent": "Asia"}),
    ("TM", {"name": "Turkmenistan", "continent": "Asia"}),
    ("TV", {"name": "Tuvalu", "continent": "Oceania"}),
    ("UG", {"name": "Uganda", "continent": "Africa"}),
    ("UA", {"name": "Ukraine", "continent": "Europe"}),
    ("AE", {"name": "United Arab Emirates", "continent": "Asia"}),
    ("GB", {"name": "United Kingdom", "continent": "Europe"}),
    ("US", {"name": "United States", "continent": "North America"}),
    ("UY", {"name": "Uruguay", "continent": "South America"}),
    ("UZ", {"name": "Uzbekistan", "continent": "Asia"}),
    ("VU", {"name": "Vanuatu", "continent": "Oceania"}),
    ("VA", {"name": "Vatican City", "continent": "Europe"}),
    ("VE", {"name": "Venezuela", "continent": "South America"}),
    ("VN", {"name": "Vietnam", "continent": "Asia"}),
    ("YE", {"name": "Yemen", "continent": "Asia"}),
    ("ZM", {"name": "Zambia", "continent": "Africa"}),
    ("ZW", {"name": "Zimbabwe", "continent": "Africa"}),
    ("None", {"name": "None", "continent": "None"})
])
